col name for a100
SELECT 
    RECID,
    RESETLOGS_CHANGE#,  -- 인카네이션 시작 SCN
    THREAD#,
    SEQUENCE#,
    FIRST_CHANGE#,      -- 로그 시작 SCN
    NEXT_CHANGE#,       -- 로그 종료 SCN
    NAME
FROM V$ARCHIVED_LOG
ORDER BY RESETLOGS_CHANGE# ASC, SEQUENCE# ASC;